import pytest
from unittest.mock import patch, MagicMock
from app.optimizer.ai_engine import AIOptimizerEngine
from app.tokenizer.openai_tokenizer import OpenAITokenizer
from app.config.env import env

@pytest.fixture
def mock_env(monkeypatch):
    monkeypatch.setattr(env, "OPENAI_API_KEY", "test-key-123")

@pytest.mark.asyncio
async def test_ai_engine_compresses_prompt_successfully(mock_env):
    tokenizer = OpenAITokenizer()
    engine = AIOptimizerEngine(tokenizer)
    
    # Original prompt is long
    original_prompt = "Hello there. I would like to tell you that this is a very long prompt with a lot of words."
    
    # Compressed prompt is shorter
    compressed_prompt = "Short prompt."
    
    mock_response = MagicMock()
    mock_response.status_code = 200
    mock_response.json.return_value = {
        "choices": [{"message": {"content": compressed_prompt}}]
    }
    
    # Mock httpx.AsyncClient
    with patch("httpx.AsyncClient") as mock_client_class:
        mock_client_instance = mock_client_class.return_value.__aenter__.return_value
        mock_client_instance.post.return_value = mock_response
        
        new_prompt, metadata = await engine.optimize(original_prompt)
        
        assert new_prompt == compressed_prompt
        assert metadata.tokens_saved > 0
        assert "ai_compression" in metadata.operations_applied

@pytest.mark.asyncio
async def test_ai_engine_rejects_longer_compression(mock_env):
    tokenizer = OpenAITokenizer()
    engine = AIOptimizerEngine(tokenizer)
    
    original_prompt = "Short"
    # AI accidentally generates a much longer prompt
    bad_compressed_prompt = "This is a very long text that the AI generated by mistake"
    
    mock_response = MagicMock()
    mock_response.status_code = 200
    mock_response.json.return_value = {
        "choices": [{"message": {"content": bad_compressed_prompt}}]
    }
    
    with patch("httpx.AsyncClient") as mock_client_class:
        mock_client_instance = mock_client_class.return_value.__aenter__.return_value
        mock_client_instance.post.return_value = mock_response
        
        new_prompt, metadata = await engine.optimize(original_prompt)
        
        # It should fallback to original
        assert new_prompt == original_prompt
        assert metadata.tokens_saved == 0
        assert "ai_compression" not in metadata.operations_applied

@pytest.mark.asyncio
async def test_ai_engine_handles_api_failure(mock_env):
    tokenizer = OpenAITokenizer()
    engine = AIOptimizerEngine(tokenizer)
    original_prompt = "Some long text here"
    
    with patch("httpx.AsyncClient") as mock_client_class:
        mock_client_instance = mock_client_class.return_value.__aenter__.return_value
        # Simulate network error
        mock_client_instance.post.side_effect = Exception("API Down")
        
        new_prompt, metadata = await engine.optimize(original_prompt)
        
        assert new_prompt == original_prompt
        assert metadata.tokens_saved == 0
        assert "ai_compression" not in metadata.operations_applied

@pytest.mark.asyncio
async def test_ai_engine_skips_without_api_key(monkeypatch):
    monkeypatch.setattr(env, "OPENAI_API_KEY", "")
    
    tokenizer = OpenAITokenizer()
    engine = AIOptimizerEngine(tokenizer)
    original_prompt = "Some long text here"
    
    new_prompt, metadata = await engine.optimize(original_prompt)
    
    assert new_prompt == original_prompt
    assert metadata.tokens_saved == 0
